name: SimplySleep
version: 1.0.5
main: me.pulz.simplysleep.SimplySleep
api-version: 1.18
authors: [_Pulz]
description: Check and reset your sleep statistics to manage Phantoms
commands:
  sleep:
    description: Resets your sleep statistics
    permission: simplysleep.sleep
    usage: /<command>
  sleeptime:
    description: Outputs the time since your last slept, in minecraft time
    permission: simplysleep.sleeptime
    usage: /<command>
  adddays:
    description: Adds the specified number of days to the time since last sleep
    permission: simplysleep.adddays
    usage: /<command>